# -*- coding: utf-8 -*-
"""9주

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGkHR0LIvGlR5Qor42f9t_fJZHDDxPB9
"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

import matplotlib.pyplot as plt
import pandas as pd
#한글 폰트 지정
plt.rc('font',family='NanumBarunGothic')
#음수 값 표시 가능
plt.rcParams['axes.unicode_minus'] = False

df = pd.read_csv('/content/행정구역별인구현황.csv',)
df

df['행정구역'] = df['행정구역'].str.split('(').str[0]
df

df.columns = ['행정구역','총인구수','세대수','세대당인구수','남자인구수','여자인구수','남여비율']
df

df = df.drop(index= 0, axis =1)
df

plt.figure(figsize=(8,8))
plt.pie(x = df['총인구수'],labels = df['행정구역'],autopct='%.2f%%')
plt.show()

df_t = df.sort_values('총인구수', ascending= False)

plt.figure(figsize=(10,3))
plt.bar(df_t['행정구역'],df_t['총인구수'],color='red')
plt.title('행정구역별총인구수')
plt.grid()
plt.xticks(rotation= 45)

plt.show()

df_g = df.sort_values('세대당인구수', ascending= False)

plt.figure(figsize=(10,5))
plt.plot(df_g['행정구역'],df_g['세대당인구수'],color='green',marker = 'o')
plt.xticks(rotation=45)
plt.title('가구당 인구수')
plt.grid()

df_t['남녀차이']=df_t['여자인구수'] - df_t['남자인구수']

df_t = df_t.sort_values('남녀차이', ascending= False)

plt.bar(df_t['행정구역'],df_t['남녀차이'],color = 'red')
plt.xticks(rotation=45)
plt.grid()
plt.title('행정구역 성비')

plt.show()

df_age = pd.read_csv('/content/연령별인구현황.csv',)
df_age

df_age['행정구역']=df_age['행정구역'].str.split('(').str[0]
df_age

df_age.set_index('행정구역',inplace=True)
df_age

df_age = df_age.drop(columns=['2023년09월_계_총인구수','2023년09월_계_연령구간인구수'])
df_age

import numpy as np

df_age.columns = np.arange(0,101)
df_age

plt.figure(figsize=(5,6))
plt.barh(df_age.columns,df_age.iloc[0],color='g')
plt.grid()
plt.title('연령별인구분포')
plt.show()